[pytest]
DJANGO_SETTINGS_MODULE = aforro_project.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = --cov=apps --cov-report=html --cov-report=term-missing
